xvidcore: fix build with gcc15
- add patch from fedora

Fixes build failure with gcc15:
```
In file included from ../../src/bitstream/bitstream.h:31,
                 from ../../src/decoder.c:40:
../../src/bitstream/../encoder.h:45:13: error: 'bool' cannot be defined via 'typedef'
   45 | typedef int bool;
      |             ^~~~
../../src/bitstream/../encoder.h:45:13: note: 'bool' is a keyword with '-std=c23' onwards
../../src/bitstream/../encoder.h:45:1: warning: useless type name in empty declaration
   45 | typedef int bool;
      | ^~~~~~~
```

(cherry picked from commit 7f3f13c49233a4d93b529fa336ea444275f4275f)